version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "learnin-sam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1lmu99ss7kbpq"
s3_prefix = "learnin-sam"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
